### ISSUE TITLE
Can jira worklog helper extension work in android based browser kiwi?

### ISSUE THREAD

**Issue by swamidridapada** [alfeugds/jiraworklogtool#37] opened 2020-05-04 11:39 UTC
Need help

**Comment by alfeugds** [comment] 2020-05-04 11:49
Hi!
It seems that Kiwi browser supports chrome extensions, so you might try installing the extension and see if it works.

https://www.guidingtech.com/install-chrome-extensions-kiwi-browser/

I never tried though. Let me know if you have any issues.

**Comment by swamidridapada** [comment] 2020-05-04 12:09
Namaskaram 

I tried and I am able to add the worklogs. And push data into jira server 
But I m not able to pull data ie not able to load the worklog / modify them

**Comment by alfeugds** [comment] 2020-05-04 13:14
I see.

I don't have an android with kiwi browser right now so I can't troubleshoot it.

One thing that may help investigating the issue is the errors in the console, along with the stack trace.

Are you able to use it with chrome for now?

**Comment by alfeugds** [comment] 2020-09-19 16:40
I'm closing this issue. Let me know if you still need it and provide the console erros so that I can investigate further.

**Closed by alfeugds** 2020-09-19 16:40 UTC
